//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShivamEComFace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> Discount { get; set; }
        public System.DateTime ShipDate { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal Total { get; set; }
        public int OrderID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int Sort { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
